dataset:
  name: "apollo2506/eurosat-dataset"
  sub_dir: "EuroSAT"
  seed: 42
  input_shape: [224, 224, 3]

data:
  image_size: [224, 224]
  batch_size: 32
  shuffle_buffer_size: 100

training:
  epochs_frozen: 1
  epochs_finetune: 1
  learning_rate_frozen: 0.001
  learning_rate_finetune: 0.00001
  fe_early_stop_patience: 2
  ft_early_stop_patience: 2
  fe_reduce_patience: 1
  ft_reduce_patience: 1
  fe_min_lr: 1e-7
  ft_min_lr: 1e-8

fine_tuning:
  fine_tune_last_n_layers: 30

artifacts:
  model_dir: "models"
  best_model_name: "models/best_model.keras"
  fe_best_model_name: "models/best_model_feature_extraction_smoke.keras"
  ft_best_model_name: "models/best_model_finetuned_smoke.keras"

smoke_test:
  enabled: true
  train_batches: 5
  val_batches: 2
  test_batches: 2